# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=60, verbose_name='cor')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='quilometragem')),
                ('engine', models.PositiveIntegerField(default=0, verbose_name='motor')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Model')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['model'],
            },
        ),
    ]
